# Generated by Django 6.0.5 on 2026-08-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')]),
        ),
    ]
